### ISSUE TITLE
Escaping org source blocks

### ISSUE THREAD

**Issue by xenodium** [floscr/blog.florianschroedl.com#1]
> until I figure out how to include escaping in source blocks

Does this work?

```
,#+begin_src ${1:`(+yas/org-last-src-lang)`}
  ...
,#+end_src
```

**Comment by floscr** [comment]
No, I think I'll have to adapt the component from `https://github.com/orgapp/orgajs/tree/master/packages/gatsby-theme-blorg`
But thank you :slightly_smiling_face:
